# Generated by Django 5.0.2 on 2024-02-19 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса и варианты ответа')),
                ('true_answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('user_answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='MyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок теста')),
                ('score', models.IntegerField(default=0, verbose_name='Результат теста')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='study.material', verbose_name='Материал')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tests', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
