# Generated by Django 5.0.2 on 2024-02-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0002_alter_mytest_options_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mytest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='my_tests.mytest', verbose_name='Мой тест'),
        ),
    ]
