# Generated by Django 5.0.2 on 2024-02-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0003_question_mytest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_answer',
        ),
    ]
